language: ruby
rvm:
  - "1.9.3"
  - "2.2.0"
  - "2.3.4"
  - "2.4.1"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y graphviz

script: bundle exec "cd test; ruby ts_bud.rb"
